[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dlmm_swapper = "7QJCkDU8eEGtarKDNNbLgFCZLfp3QJuxJ8gkp1iLbSTc"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#cluster = "https://api.devnet.solana.com"
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
